services:
  postgres:
    image: postgres:16
    container_name: art_gallery_postgres
    environment:
      POSTGRES_DB: art_gallery
      POSTGRES_USER: art_gallery
      POSTGRES_PASSWORD: art_gallery
    ports:
      - "5432:5432"
    volumes:
      - art_gallery_pgdata:/var/lib/postgresql/data

volumes:
  art_gallery_pgdata:
